### ISSUE TITLE
Need more description how to run it

### ISSUE THREAD

**Issue by aspats** [jcalazan/youtube-audio-dl#1]
Hi!

I want to use youtube-audio-dl, but I can't. 
I try 
git clone https://github.com/jcalazan/youtube-audio-dl.git
pip install -U -r requirements.txt
./manage.py runserver

But I got this error:
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'youtubeadl.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named settings

Maybe can you help to solve it?

**Comment by jcalazan** [comment]
Hey sorry, didn't put much info as I plan to rewrite it (current code is ugly, wrote it on a weekend).

The issue is because I separated the settings file.  Simply do `./manage.py runserver --settings=settings.local`

**Comment by aspats** [comment]
Thank you!!!!
Now ./manage.py runserver --settings=settings.local works perfect.
I try to create database with ./manage.py syncdb --settings=settings.local
but I get an error.

**Comment by jcalazan** [comment]
Hey aspats,

What's the error message during `syncdb`? You'll probably also need to run `migrate` (South), though `syncdb` should work fine.

**Comment by aspats** [comment]
jcalazan,

Sorry, that I reply later. Now I solved everything it is working :). Just I didn't saw that you was using postresql. So I installed postgresql. After that I had some doubts, but I figure out. Than you @jcalazan !!!

**Comment by jcalazan** [comment]
Np man, glad you got it running! :)
