### ISSUE TITLE
Fist docker-compose run fails

### ISSUE THREAD

**Issue by epicserve** [jcalazan/youtube-audio-dl#6]
After running ``docker-compose run django pip install -r requirements.txt`` I get the following:

```
...

Successfully installed Django django-braces django-compressor django-debug-toolbar django-extensions django-grappelli celery flower gunicorn ipdb ipython psycopg2 Werkzeug youtube-dl six django-appconf sqlparse pytz billiard kombu tornado babel futures anyjson amqp certifi backports.ssl-match-hostname
Cleaning up...
  Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 243, in run
    requirement_set.cleanup_files(bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1047, in cleanup_files
    rmtree(dir)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 29, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py",
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/youtube-audio-dl/build/Django/tests/staticfiles_tests/apps/test/static/test'

  Storing complete log in /root/.pip/pip.log
```

**Comment by jcalazan** [comment]
Hmm...were any of these files or directories open while pip install was running?  It looks like it was trying to do a cleanup (at the end pip deletes the `build` directory) but it couldn't.

**Comment by epicserve** [comment]
Same result:

```
# remove all containers
$ docker rm $(docker ps -a -q)
$ rm -rf ~/dockerfiles
$ docker-compose run django pip install -r requirements.txt

Successfully installed Django django-braces django-compressor django-debug-toolbar django-extensions django-grappelli celery flower gunicorn ipdb ipython psycopg2 Werkzeug youtube-dl six django-appconf sqlparse pytz billiard kombu tornado babel futures anyjson amqp certifi backports.ssl-match-hostname
Cleaning up...
  Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 243, in run
    requirement_set.cleanup_files(bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1047, in cleanup_files
    rmtree(dir)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 29, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/youtube-audio-dl/build/Django/tests/staticfiles_tests/apps/test/static/test'

  Storing complete log in /root/.pip/pip.log

```

**Comment by epicserve** [comment]
I removed all containers and docker images and deleted and re-cloned youtube-audio-dl. Tried it again and not this part worked. However I'm still running into issue #7.
